[package]
name = "risc-v-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }

[[bin]]
name = "risc-v-sim"
path = "main.rs"
